apiVersion: apps/v1
kind: Deployment
metadata:
  name: loco-demo-deployment
  labels:
    app: loco-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loco-app
  template:
    metadata:
      labels:
        app: loco-app
    spec:
      containers:
      - name: loco-app
        image: locoacr.azurecr.io/loco/locoapp:v1
        ports:
        - containerPort: 7000
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loco-demo-deployment-hpa
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loco-demo-deployment
  targetCPUUtilizationPercentage: 60                  
---
apiVersion: v1
kind: Service
metadata:
  name: loco-demo-app-service
  labels:
    app: loco-app
spec:
  type: LoadBalancer
  selector:
    app: loco-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 7000  
